lblod/form-content-service

app.ts
form-repository.ts

this allows fetching the form definition for a given form in the database.
The current model used by the form builder is used, but it feels like this is very much something we should change (?)
the form is requested from the database through SEAS so access rights are taken into account. This has been tested by running this service locally in concert with the rest of the LMB app

[LMB-26] feat: allow fetching the form definition

---

.eslintignore
.eslintrc.cjs
app.ts
declarations.d.ts
form-validator.ts
package-lock.json
package.json
queries/getPathsForFields.ts
queries/getPathsForGenerators.ts
utils.ts

This creates a construct query to fetch information necessary to render an instance of a form definition.
That construct query can then be used for:
- fetching all data for a form from a mu-auth aware triple store (SEAS)
- fetching only the form data from a form instance posted by the frontend
- deleting all form data from the backend and replacing it with the new form content (this is a little hardcore, we may want to be nicer and only replace the delta)

Construct for form paths

---

README.md
form-validator.ts

This way our forms can use nested concepts instead of custom components

Add support for SPARQL property paths in form definitions

---

form-validator.ts
utils/update-predicate-in-ttl.ts

LMB-370
We are adding a predicate dct:modified to each subject that is being updated through the form-content-service. This so we do not have to add hidden fields to each entity in the backend and so that we can have always see when an entity is modified.
In the predicates of each subject that you update through a form should be the dct:modified with the datetime of the change

LMB-370: dct:modified to every instance that is being updated

---

domain/data-access/comunica-repository.ts

By searching for the name of a field in the formTtl it was no longer possible to use the mu:uuid etc (which is no form field) as a label. Now this name is optional and defaults to "label" if no corresponding form field is found.

default instance label name to label if no corresponding form field exists

---

helpers/ttl-helpers.ts
utils/update-predicate-in-ttl.ts

Issue: LMB-370
Description: When creating or updating the type of dct:modified is incorrect. What we used is **datetime** what it should be **dateTime**. The difference is the capital T in the type.
When datetime is used the helpers will return the dateTime type how it supposed to be.

LMB-370: dct:modified bug resolve resource can't read type datetime

---

README.md
controllers/form-definitions.ts
domain/data-access/comunica-repository.ts
domain/data-access/form-extension-repository.ts
services/forms-from-config.ts

I added a form validity check for all forms that are loaded into this service, so the service can fail early when an invalid form is loaded in. Before a hard to debug error was thrown when the request for all form names came in, giving the developer no leads on what form might be causing issues.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Kill the form-content-service
- Break one of the form.ttls in the backend by removing a prefix or a triple or the whole form.ttl altogether! ![image](https://github.com/lblod/form-content-service/assets/55446974/c859a0f5-f705-4c94-beda-0f926e8e2baa)
- Start the form-content-service
- After starting up, the service should crash. …

Log Clear Errors When Invalid Forms Are Loaded

---

.github/pull_request_template.md

Removing link to issue in the description as we don't want to link or private project issues in our Github PR's.

LMB-405: remove link to issue in description

---

docker-compose.debug.yml
services/forms-from-config.ts

When changing form TTLs in `app-lokaal-mandatenbeheer`, the form-content-service didn't reload, and this lead to some confusion and inconvenience. With this PR, combined with a small change in the `mu-javascript-template`, the forms should update automatically without having to `kill` and `up` the form-content-service.
- Start the `form-content-service`
- Go to the forms module in the browser and pick a form
- Change the formTTL of that form in `app` `/config/form-content`
- Check in the browser if the form has changed

Load forms into /config so they can be monitored by mu-javascript-template

---

README.md
domain/data-access/form-extension-repository.ts
services/form-extensions.ts

It is possible to extend forms in the form-content service. E.g. forms bestuursorgaan-ext-example extend the form bestuursorgaan. The form-content merges these forms but if duplicate form settings (triples belonging to the form object) are deleted from the base form and taken from the extension. This is alright for the triples such as mu:uuid, but for other properties such as targetType, targetLabel and prefix it would be better if they were only overwritten if they exist in the form extension. 
This would mean they are no longer required, they are still required for a regular form, but if they are not defined in the form extension, the ones from the base form can just be used.
- /
- Remove for example the `form:targetType` from the …

LMB-237: Extension forms should get the targetType and label from the base form

---

config/interceptors.ts
domain/data-access/form-repository.ts
services/forms-from-config.ts

Add logic to allow adding a `interceptors.ts` file to the config that will get called when fetching conceptSchemes defined in the form. This allows populating dropdown fields (like `displayTypes:conceptSchemeSelector`) with any (possibly dynamic) data in the triplestore, without needing to make it an actual concept. It also allows filtering out conceptScheme triples that form-content-service fetched, giving extra flexibility.
If not defined, the interceptor does nothing, so this is a non-breaking change.
In the future it would be nice to force forms to be put in a subfolder (e.g. /forms) in the config directory, so other configurations can be added more easily.
It wasn't clear to me where in the Readme this should be explained.
Create a form with some dropdown and a custom uri for the …

Add interceptor logic to allow custom conceptScheme fetching

---

services/form-definitions.ts

This is a similar strategy as what has been done in `getHistoryInstance`.
I am currently not sure what is to blame here,
i.e. who is not respecting a standard (js-template or rdfLib?)

Workaround: adding the prefix xsd when returning the form and meta.

---

domain/data-access/form-extension-repository.ts
helpers/ttl-helpers.ts
services/custom-forms.ts
services/form-extensions.ts

See linked PR 
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/350

complex paths in library fields, with support for generators

---

Dockerfile
app.ts
controllers/form-definitions.ts
declarations.d.ts
docker-compose.debug.yml
domain/data-access/form-extension-repository.ts
domain/data-access/form-repository.ts
helpers/ttl-helpers.ts
services/custom-forms.ts
services/form-definitions.ts
services/form-extensions.ts
services/forms-from-config.ts
types.ts

Allows the creation of custom form extensions by adding fields to forms and removing fields that have been added in this way (only from custom forms)
see https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/449

allow creating custom form extensions

---

controllers/form-definitions.ts
controllers/form-instances.ts
services/form-definitions.ts
services/form-instances.ts

Now that we can create edit form definitions and instances we also need to remove them properly.  These endpoints will help the frontend to handle the removal of the forms/instances of a form.
1. Use it together with the frontend
2. Queries should be fast
3. All remains of the form/instances should be removed
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/524

LMB-1218 | Find and remove usages of the form definition

---

services/custom-forms.ts

We want to enable the field option to have a conceptscheme added to it. This makes it possible to show conceptscheme selector in the frontend.
Together with the frontend you should be able to add a conceptscheme to a codelist field.
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/410
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/528

LMB-1500 | Custom form fields can be conceptscheme selector

---

services/custom-forms.ts

We could not remove custom fields from custom forms as it checked if the type was a form:Extension. This is not necessary, isCustom is enough.
Remove a field from a custom form + form extension
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/540

lmb-1529 | Removing a field is possible for all isCustom fields

---

controllers/form-instances.ts
domain/data-access/comunica-repository.ts
services/custom-forms.ts
services/form-definitions.ts

Add missing predicate on creation of custom form
When creating an "eigen" form the first field should also have the predicate isCustomForm and you should see the show in summary toggle
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/564
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/437

lmb-1515: add ext:isCustomForm to the generated forms

---

domain/data-access/comunica-repository.ts
services/custom-forms.ts
services/form-instances.ts

Summary fields should always follow the order of the fields
- instances table
- configure columns 
- link to instance list
1. create a custom form and add showInSummary to atleast 2 fields
2. These field labels should be shown in the instances table in the order of the fields
3. Move the fields around, and the instance table + configuration should follow this order
4. When linking to a form you have the table that show the selected and the table that shows all instances, make sure these are also following the order
- https://github.com/lblod/ember-semantic-forms/pull/9
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/578

LMB-1532 | summary fields should be ordered

---

controllers/form-definitions.ts
services/form-definitions.ts

We need a check to see if the form is used in configuration of a custom form so we can disallow it to be removed.
Use the frontend PR to see if the usages are found
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/577

lmb-1593 | add end point to check if the form definition is used in a custom form configuration
