lblod/form-content-service

.woodpecker/.latest.yml, .woodpecker/.release.yml, .woodpecker/.test-build.yml
stole config from: https://github.com/lblod/worship-positions-graph-dispatcher-service-loket/tree/master
=> [LMB-24] add woodpecker config

.dockerignore, .eslintignore, .eslintrc.cjs, .gitignore, .prettierignore, .prettierrc.cjs, .woodpecker/.test-build.yml, Dockerfile, app.ts, form-repository.ts, form-validator.ts, package-lock.json, package.json, types.ts, utils.ts
this allows posing new instances for a form. These instances are not validated except for loading them into a forking store and fetching the resulting triples. validation is a separate story that builds on the construct query for a form.
=> [LMB-25] post form instances

app.ts, form-repository.ts
=> [LMB-36] load forms in config directory and treat names as id

app.ts, form-repository.ts, utils.ts
this adds a route to fetch a form instance. It uses the construct query created in https://github.com/lblod/form-content-service/pull/7 so better review that PR first
=> fetch form instance

Dockerfile, README.md, app.ts, queries/formInstances.ts, types.ts, utils.ts
Add endpoint to fetch form instances.
=> Fetch form instances

app.ts, package-lock.json, package.json
this allows the use of async route handlers without fear of unhandled promise rejections
=> fix: use express-promise-router

README.md, app.ts, controllers/form-definitions.ts, controllers/form-instances.ts, domain/data-access/comunica-repository.ts, domain/data-access/form-repository.ts, services/form-instances.ts
replace it by form:targetType and form:targetLabel
=> remove ext:label predicate in forms

README.md, domain/data-access/comunica-repository.ts, domain/data-access/form-repository.ts, form-validator.ts, services/form-instances.ts, types.ts
write a tombstone for all instances where the type predicate is deleted when the form instance is deleted
=> add tombstone on delete

controllers/form-instances.ts, domain/data-access/comunica-repository.ts, domain/data-access/form-repository.ts, domain/data-access/user-repository.ts, helpers/ttl-helpers.ts, package-lock.json, package.json, services/form-definitions.ts, services/form-instances.ts
Once you add https://github.com/lblod/app-lokaal-mandatenbeheer/pull/81 to the app, the mandataris form will start tracking history. You can validate this by creating/updating a mandataris and running the following query:
```
SELECT ?historyGraph  ?s ?pp ?oo WHERE {
?historyGraph ?p <mandatarisuri>.
GRAPH ?historyGraph {
?s ?pp ?oo.
}
}
```
This will show the historical entry for the mandataris you created. The metadata will be added to the <http://mu.semte.ch/graphs/formHistory>  graph and will contain the link to the user, time of entry and the link between the history graph and the original uri.
easiest way to verify is to just run
```
SELECT * WHERE {
GRAPH <http://mu.semte.ch/graphs/formHistory> {
?s ?p ?o.
}
}
```
=> add form history

.gitignore, app.ts, controllers/form-definitions.ts, controllers/form-instances.ts, domain/data-access/form-repository.ts, services/form-instances.ts
The easiest way to review and test this pr is to use the frontend branch here: https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/124
The mandataris and fractie forms have history tracking enabled.
=> allow fetching history items

controllers/form-instances.ts, services/form-instances.ts
can be tested in https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/132
=> allow the frontend to ask for an ad hoc version to be created

form-validator.ts
=> LMB-370: format the date to ISO string

.github/pull_request_template.md
Create a template file to everyone knows what the implementation does
=> LMB-405: add PR template

helpers/ttl-helpers.ts
Adding a log to know what the type and length of ttl is when the Lexer issue pops up.
=> LMB-229: log for ttl type and length

helpers/ttl-helpers.ts
create a new parser when moving ttl to store, return on reject
open a form in the frontend after pulling this version of the form-content service
=> create a new parser when moving ttl to store, return on reject

controllers/form-definitions.ts, services/custom-forms.ts
Allow chaning the order of a field, but keep non extending fields fixed.
see linked pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/457
=> allow changing field order

controllers/form-definitions.ts, services/custom-forms.ts
We need an extra endpoint for updating a custom field.
Us this branch togheter with the frontend for updating a field.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/455
=>  lmb 182 | add update field endpoint

controllers/form-definitions.ts, services/custom-forms.ts
We want to be able to add validations to our library entree.
Add the telephone field to your custom fields form and see if the validations get triggered.
=> Lmb 1226 can make custom field required

domain/data-access/comunica-repository.ts, domain/data-access/form-extension-repository.ts, domain/data-access/form-repository.ts, form-validator.ts, package-lock.json, package.json, services/form-extensions.ts, tsconfig.json
To prevent sparql injection we need to escape all user input value with the mu package sparqlEscape methods
Go throught the code and places where it should also be escaped by the mu package
- https://github.com/lblod/mandataris-service/pull/86
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/359
=> lmb-1055 | Escape all user inputted values in the sparql queries 

app.ts, controllers/form-instances.ts, controllers/instance-table.ts, domain/data-access/comunica-repository.ts, domain/data-access/form-repository.ts, services/custom-forms.ts, services/form-instances.ts, types.ts
In the `/forms` route for a form we want to make the columns configurable, this should only be done when there is a custom form for this formId.
Go to the forms route and configure the columns
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180
- https://github.com/lblod/ember-semantic-forms/pull/4
=> Lmb 1228  | v2 configurable instance columns

controllers/instance-table.ts, domain/data-access/form-repository.ts, package-lock.json, package.json, services/custom-forms.ts, services/form-instances.ts, types.ts, utils/get-custom-form-field-value.ts, utils/json-to-csv-string.ts
Add an endpoint for downloading the instance table as csv.
Checkout the frontend branch and download the content of your instance table
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/480
=> Lmb 1230 export the instance table as csv

.woodpecker/.latest.yml, .woodpecker/.release.yml, .woodpecker/.test-build.yml
Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180
=> Add multiarch build

controllers/custom-forms.ts, controllers/form-definitions.ts, services/custom-forms.ts
Update the service so we can edit and update fields and custom forms
Test it together with the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/542
=> Lmb 1478 edit fields in sidebar

domain/data-access/form-repository.ts, helpers/ttl-helpers.ts
We where splitting our ttl code string on the do string.split('.'). We should not be doing that => find a solution
Everything should work as it was + you can now use user input strings with dots in it
=> lmb-1571: do split the string on a dot (.)

app.ts, controllers/custom-forms.ts, controllers/form-definitions.ts, controllers/form-instances.ts, domain/data-access/comunica-repository.ts, domain/data-access/form-repository.ts, services/custom-forms.ts, services/form-definitions.ts, services/form-instances.ts, types.ts
Update the service so we can add links to other forms. 
Test together with the frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/536
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/416
=> LMB-1502 | Allow linking to other form instances

controllers/custom-forms.ts, controllers/form-instances.ts, services/custom-forms.ts
allow getting usage of an instance, with it's using instance, form, id, uri
see linked frontend pr
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/548
=> allow getting usage of an instance, with it's using instance, form, id, uri

services/custom-forms.ts, services/display-type-validations.ts
Allowing to pass on a displayType constraint without a path. The path is get from the field.
The service is should not crash 
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/593
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/449
=> LMB-1681 | Custom url field
